# Generated by Django 5.2.11 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Armazenamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("tipo", models.CharField(choices=[("SSD_SATA", "SSD SATA"), ("SSD_NVME", "SSD NVMe"), ("HDD", "HDD")], max_length=20)),
                ("interface", models.CharField(choices=[("SATA3", "SATA III"), ("M2_NVME", "M.2 NVMe"), ("M2_SATA", "M.2 SATA")], max_length=20)),
                ("capacidade_gb", models.PositiveIntegerField()),
                ("velocidade_leitura", models.PositiveIntegerField(help_text="MB/s")),
                ("velocidade_escrita", models.PositiveIntegerField(help_text="MB/s")),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/armazenamentos/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="armazenamentos", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Armazenamento",
                "verbose_name_plural": "Armazenamentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fonte",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("potencia_watts", models.PositiveSmallIntegerField()),
                ("certificacao", models.CharField(choices=[("GENERIC", "Genérica"), ("80PLUS", "80 Plus"), ("80PLUS_BRONZE", "80 Plus Bronze"), ("80PLUS_SILVER", "80 Plus Silver"), ("80PLUS_GOLD", "80 Plus Gold"), ("80PLUS_PLATINUM", "80 Plus Platinum"), ("80PLUS_TITANIUM", "80 Plus Titanium")], default="GENERIC", max_length=20)),
                ("modular", models.BooleanField(default=False)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/fontes/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fontes", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Fonte",
                "verbose_name_plural": "Fontes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="MemoriaRAM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("tipo", models.CharField(choices=[("DDR4", "DDR4"), ("DDR5", "DDR5")], max_length=10)),
                ("capacidade_gb", models.PositiveSmallIntegerField()),
                ("quantidade_modulos", models.PositiveSmallIntegerField(default=1)),
                ("frequencia_mhz", models.PositiveIntegerField()),
                ("latencia", models.CharField(blank=True, max_length=20)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/memorias/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="memorias_ram", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Memória RAM",
                "verbose_name_plural": "Memórias RAM",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PlacaDeVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("gpu_chip", models.CharField(max_length=100)),
                ("memoria_gb", models.PositiveSmallIntegerField()),
                ("tipo_memoria", models.CharField(max_length=30)),
                ("interface", models.CharField(max_length=30)),
                ("consumo_watts", models.PositiveSmallIntegerField()),
                ("fonte_recomendada_watts", models.PositiveSmallIntegerField()),
                ("comprimento_mm", models.PositiveSmallIntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/placas_video/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="placas_video", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Placa de vídeo",
                "verbose_name_plural": "Placas de vídeo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PlacaMae",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("socket", models.CharField(choices=[("LGA1700", "LGA1700"), ("LGA1851", "LGA1851"), ("LGA1200", "LGA1200"), ("AM5", "AM5"), ("AM4", "AM4")], max_length=20)),
                ("chipset", models.CharField(max_length=80)),
                ("tipo_memoria", models.CharField(choices=[("DDR4", "DDR4"), ("DDR5", "DDR5")], max_length=10)),
                ("slots_ram", models.PositiveSmallIntegerField()),
                ("max_memoria_gb", models.PositiveSmallIntegerField()),
                ("frequencia_max_ram", models.PositiveIntegerField(help_text="MHz")),
                ("form_factor", models.CharField(choices=[("ATX", "ATX"), ("MATX", "mATX"), ("ITX", "ITX"), ("EATX", "E-ATX")], max_length=10)),
                ("tem_slot_m2", models.BooleanField(default=True)),
                ("quantidade_m2", models.PositiveSmallIntegerField(default=0)),
                ("portas_sata", models.PositiveSmallIntegerField(default=0)),
                ("slot_pcie_x16", models.PositiveSmallIntegerField(default=1)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/placas_mae/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="placas_mae", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Placa-mãe",
                "verbose_name_plural": "Placas-mãe",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Processador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("socket", models.CharField(choices=[("LGA1700", "LGA1700"), ("LGA1851", "LGA1851"), ("LGA1200", "LGA1200"), ("AM5", "AM5"), ("AM4", "AM4")], max_length=20)),
                ("cores", models.PositiveSmallIntegerField()),
                ("threads", models.PositiveSmallIntegerField()),
                ("frequencia_base", models.DecimalField(decimal_places=2, max_digits=4)),
                ("frequencia_turbo", models.DecimalField(decimal_places=2, max_digits=4)),
                ("tdp", models.PositiveSmallIntegerField(help_text="Watts")),
                ("tem_video_integrado", models.BooleanField(default=False)),
                ("geracao", models.CharField(blank=True, max_length=60)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="componentes/processadores/")),
                ("descricao", models.TextField(blank=True)),
                ("disponivel", models.BooleanField(default=True)),
                ("fabricante", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="processadores", to="website.fabricante")),
            ],
            options={
                "verbose_name": "Processador",
                "verbose_name_plural": "Processadores",
                "ordering": ["nome"],
            },
        ),
    ]
