# Generated by Django 5.2.11 on 2026-08-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_componentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Montagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.armazenamento')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.fonte')),
                ('memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.memoriaram')),
                ('placa_de_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.placadevideo')),
                ('placa_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.placamae')),
                ('processador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montagens', to='website.processador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Montagem',
                'verbose_name_plural': 'Montagens',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=20)),
                ('componente_tipo', models.CharField(max_length=40)),
                ('componente_nome', models.CharField(blank=True, max_length=120)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('montagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='website.montagem')),
            ],
            options={
                'verbose_name': 'Histórico de Montagem',
                'verbose_name_plural': 'Históricos de Montagem',
                'ordering': ['-data'],
            },
        ),
    ]
