from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import path

from .views import (
    ArmazenamentoCreate,
    ArmazenamentoDelete,
    ArmazenamentoDetail,
    ArmazenamentoList,
    ArmazenamentoUpdate,
    ContatoView,
    FabricanteCreate,
    FabricanteDelete,
    FabricanteDetail,
    FabricanteList,
    FabricanteUpdate,
    FonteCreate,
    FonteDelete,
    FonteDetail,
    FonteList,
    FonteUpdate,
    IndexView,
    MemoriaRAMCreate,
    MemoriaRAMDelete,
    MemoriaRAMDetail,
    MemoriaRAMList,
    MemoriaRAMUpdate,
    MontagemCreate,
    MontagemDelete,
    MontagemDetail,
    MontagemFinalizar,
    MontagemList,
    MontagemUpdate,
    PlacaDeVideoCreate,
    PlacaDeVideoDelete,
    PlacaDeVideoDetail,
    PlacaDeVideoList,
    PlacaDeVideoUpdate,
    PlacaMaeCreate,
    PlacaMaeDelete,
    PlacaMaeDetail,
    PlacaMaeList,
    PlacaMaeUpdate,
    ProcessadorCreate,
    ProcessadorDelete,
    ProcessadorDetail,
    ProcessadorList,
    ProcessadorUpdate,
    SobreView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("contato/", ContatoView.as_view(), name="contato"),
    path("sobre/", SobreView.as_view(), name="sobre"),

    # Autenticação: login, logout e alteração de senha reaproveitam o
    # template de auth/login.html, apenas trocando o título/botão via extra_context
    path("login/", LoginView.as_view(
        template_name="website/auth/login.html",
        extra_context={"titulo": "Entrar", "botao": "Entrar"},
    ), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("alterar-senha/", PasswordChangeView.as_view(
        template_name="website/auth/login.html",
        extra_context={"titulo": "Alterar minha senha", "botao": "Alterar Senha"},
        success_url="/",
    ), name="alterar-senha"),

    path("cadastrar/fabricante/", FabricanteCreate.as_view(), name="fabricante-create"),
    path("atualizar/fabricante/<int:pk>/", FabricanteUpdate.as_view(), name="fabricante-update"),
    path("excluir/fabricante/<int:pk>/", FabricanteDelete.as_view(), name="fabricante-delete"),
    path("listar/fabricante/", FabricanteList.as_view(), name="fabricante-list"),
    path("detalhar/fabricante/<int:pk>/", FabricanteDetail.as_view(), name="fabricante-detail"),

    path("cadastrar/processador/", ProcessadorCreate.as_view(), name="processador-create"),
    path("atualizar/processador/<int:pk>/", ProcessadorUpdate.as_view(), name="processador-update"),
    path("excluir/processador/<int:pk>/", ProcessadorDelete.as_view(), name="processador-delete"),
    path("listar/processador/", ProcessadorList.as_view(), name="processador-list"),
    path("detalhar/processador/<int:pk>/", ProcessadorDetail.as_view(), name="processador-detail"),

    path("cadastrar/placamae/", PlacaMaeCreate.as_view(), name="placamae-create"),
    path("atualizar/placamae/<int:pk>/", PlacaMaeUpdate.as_view(), name="placamae-update"),
    path("excluir/placamae/<int:pk>/", PlacaMaeDelete.as_view(), name="placamae-delete"),
    path("listar/placamae/", PlacaMaeList.as_view(), name="placamae-list"),
    path("detalhar/placamae/<int:pk>/", PlacaMaeDetail.as_view(), name="placamae-detail"),

    path("cadastrar/memoriam/", MemoriaRAMCreate.as_view(), name="memoriam-create"),
    path("atualizar/memoriam/<int:pk>/", MemoriaRAMUpdate.as_view(), name="memoriam-update"),
    path("excluir/memoriam/<int:pk>/", MemoriaRAMDelete.as_view(), name="memoriam-delete"),
    path("listar/memoriam/", MemoriaRAMList.as_view(), name="memoriam-list"),
    path("detalhar/memoriam/<int:pk>/", MemoriaRAMDetail.as_view(), name="memoriam-detail"),

    path("cadastrar/placavideo/", PlacaDeVideoCreate.as_view(), name="placavideo-create"),
    path("atualizar/placavideo/<int:pk>/", PlacaDeVideoUpdate.as_view(), name="placavideo-update"),
    path("excluir/placavideo/<int:pk>/", PlacaDeVideoDelete.as_view(), name="placavideo-delete"),
    path("listar/placavideo/", PlacaDeVideoList.as_view(), name="placavideo-list"),
    path("detalhar/placavideo/<int:pk>/", PlacaDeVideoDetail.as_view(), name="placavideo-detail"),

    path("cadastrar/armazenamento/", ArmazenamentoCreate.as_view(), name="armazenamento-create"),
    path("atualizar/armazenamento/<int:pk>/", ArmazenamentoUpdate.as_view(), name="armazenamento-update"),
    path("excluir/armazenamento/<int:pk>/", ArmazenamentoDelete.as_view(), name="armazenamento-delete"),
    path("listar/armazenamento/", ArmazenamentoList.as_view(), name="armazenamento-list"),
    path("detalhar/armazenamento/<int:pk>/", ArmazenamentoDetail.as_view(), name="armazenamento-detail"),

    path("cadastrar/fonte/", FonteCreate.as_view(), name="fonte-create"),
    path("atualizar/fonte/<int:pk>/", FonteUpdate.as_view(), name="fonte-update"),
    path("excluir/fonte/<int:pk>/", FonteDelete.as_view(), name="fonte-delete"),
    path("listar/fonte/", FonteList.as_view(), name="fonte-list"),
    path("detalhar/fonte/<int:pk>/", FonteDetail.as_view(), name="fonte-detail"),

    path("cadastrar/montagem/", MontagemCreate.as_view(), name="montagem-create"),
    path("atualizar/montagem/<int:pk>/", MontagemUpdate.as_view(), name="montagem-update"),
    path("excluir/montagem/<int:pk>/", MontagemDelete.as_view(), name="montagem-delete"),
    path("listar/montagem/", MontagemList.as_view(), name="montagem-list"),
    path("detalhar/montagem/<int:pk>/", MontagemDetail.as_view(), name="montagem-detail"),
    path("finalizar/montagem/<int:pk>/", MontagemFinalizar.as_view(), name="montagem-finalizar"),
]
